# Generated by Django 4.2.16 on 2024-11-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
